### ISSUE TITLE
Schema like errors when creating new trigger.

### ISSUE THREAD

**Issue by rgammans** [dkapell/samsara-engine#253]
When attempting to create a trigger I got the error

   `error: column "group_id" of relation "triggers" does not exist.`
running 
    `alter table triggers add column group_id int;` 

in an attempt to fix it then resulted in the error 
    `error: column "condition" of relation "triggers" does not exist` v.

**Comment by dkapell** [comment]
Added 
```
group_id int,
condition text
...
CONSTRAINT triggers_group_fk FOREIGN KEY (group_id)
        REFERENCES "groups" (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE SET NULL
```
to triggers in tables.sql
